apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: argo-rollouts-canary
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: argo-rollouts-canary
  template:
    metadata:
      labels:
        app: argo-rollouts-canary
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 10s}
      - analysis:
          templates:
          - templateName: success-rate
          args:
          - name: service-name
            value: ec-specs-service-name


---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    interval: 1m
    count: 2
    # NOTE: prometheus queries return results in the form of a vector.
    # So it is common to access the index 0 of the returned array to obtain the value
#    successCondition: result[0] >= 0.95
#    failureLimit: 3
    successCondition: len(result) > 0 && result[0] >= 0.90
    failureCondition: len(result) > 0 && result[0] < 0.50
    provider:
      prometheus:
        address: http://prometheus-server.monitoring.svc.cluster.local
        query: |
          sum(irate(
            istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}",response_code!~"5.*"}[5m]
          )) /
          sum(irate(
            istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}"}[5m]
          ))
