apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: argo-rollouts-canary
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: argo-rollouts-canary
  template:
    metadata:
      labels:
        app: argo-rollouts-canary
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:green
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10s}
      - setWeight: 60
      - pause: {}
      - setWeight: 80
      - pause: {duration: 10s}
